[project]
name = "rag-core-lib"
version = "0.1.0"
description = "A python lambda layer for core rag library."
requires-python = ">=3.10"

dependencies = [
  "chonkie==1.5.0",
  "requests==2.32.5",
  "pydantic==2.12.5",
  "pendulum==3.1.0"
]
